# Generated by Django 5.2.6 on 2025-09-20 18:09

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boundless", "0004_auto_20220920_2328"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="emoji",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="gameobj",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="itemcolorvariant",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="itemcolorvariant",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="itemmetalvariant",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="itemmetalvariant",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="localizedname",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tints",
            field=models.ManyToManyField(related_name="+", to="boundless.item"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="atlas_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
            ),
        ),
    ]
