volumes:
  local_postgres_data: {}

services:
  boundlexx-django: &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: dev
      cache_from:
        - ghcr.io/angellusmortis/boundlexx-django
        - ghcr.io/angellusmortis/boundlexx-django-dev
        - boundlexx-django-dev
    image: boundlexx-django-dev
    depends_on:
      - boundlexx-postgres
      - boundlexx-redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: start
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: django
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-manage:
    <<: *django
    environment:
      - DJANGO_MANAGE=1
    command: ""
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: manage
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-test:
    <<: *django
    environment:
      - PYTEST=1
    command: ""
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: test
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-lint:
    <<: *django
    depends_on: []
    entrypoint: /bin/bash
    command: -c "lint-code"
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: lint
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-format:
    <<: *django
    depends_on: []
    entrypoint: /bin/bash
    command: -c "format-code"
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: format
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
      cache_from:
        - ghcr.io/angellusmortis/boundlexx-postgres
        - boundlexx-postgres
    image: boundlexx-postgres
    shm_size: 1g
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    labels:
      app.kubernetes.io/name: boundlexx-postgres
      app.kubernetes.io/component: postgres
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production
    env_file:
      - ./.env

  boundlexx-redis:
    image: redis:5.0
    command: redis-server --appendonly yes
    labels:
      app.kubernetes.io/name: boundlexx-redis
      app.kubernetes.io/component: redis
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-celery:
    <<: *django
    depends_on:
      - boundlexx-redis
      - boundlexx-postgres
    command: start-celeryworker
    environment:
      - CELERY_WORKER_QUEUES=default,distance,cache,notify,poll,shop,control
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: celery
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-celerybeat:
    <<: *django
    depends_on:
      - boundlexx-redis
      - boundlexx-postgres
    command: start-celerybeat
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: celerybeat
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-huey-consumer:
    <<: *django
    depends_on:
      - boundlexx-redis
    command: start-huey-consumer
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: huey-consumer
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production

  boundlexx-huey-scheduler:
    <<: *django
    depends_on:
      - boundlexx-redis
    command: start-huey-scheduler
    labels:
      app.kubernetes.io/name: boundlexx-django
      app.kubernetes.io/component: huey-scheduler
      app.kubernetes.io/part-of: boundlexx
      app.kubernetes.io/instance: boundlexx
      app.kubernetes.io/environment: production
