# Generated by Django 5.2.6 on 2025-09-20 18:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportedfile",
            name="exported_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
    ]
