name: Boundlexx CI/CD

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  # Run tests and linting
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fix permissions
        run: sudo chown -R 1000:1000 $GITHUB_WORKSPACE

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Pull cached images
        run: |
          docker pull ${{ env.REGISTRY }}/angellusmortis/boundlexx_postgres:latest || true
          docker pull ${{ env.REGISTRY }}/angellusmortis/boundlexx_django:latest || true
          docker pull ${{ env.REGISTRY }}/angellusmortis/boundlexx_dev_django:latest || true

      - name: Build CI images
        run: docker compose build postgres test lint

      - name: Cache dev Django image
        run: |
          docker tag boundlexx_dev_django ${{ env.REGISTRY }}/angellusmortis/boundlexx_dev_django:latest
          docker push ${{ env.REGISTRY }}/angellusmortis/boundlexx_dev_django:latest || true

      - name: Run linters
        run: docker compose run --rm lint

      - name: Run tests
        run: docker compose run --rm test

  # Build and push production images
  build-and-push:
    name: Build and Push Production Images
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Postgres
        id: meta-postgres
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/angellusmortis/boundlexx_postgres
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for Django
        id: meta-django
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/angellusmortis/boundlexx_django
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Postgres image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/postgres/Dockerfile
          push: true
          tags: ${{ steps.meta-postgres.outputs.tags }}
          labels: ${{ steps.meta-postgres.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Django image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/django/Dockerfile
          target: production
          push: true
          tags: ${{ steps.meta-django.outputs.tags }}
          labels: ${{ steps.meta-django.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
